#!/bin/sh -eu

export PATH=$HOME/.ghcup/bin:$PATH

################################################################################
# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=myxmonad

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift

################################################################################
cabal v2-build -v3 myxmonad -O2

find dist-newstyle -type f -executable -name $EXE_NAME \
     -exec cp -u '{}' $output_file ';'
